---

- name: setup user management
  hosts: awsubuntu
  become: true
  tasks:
   - name: Add a group
     group:
      name={{ item  }}
      state=present
     with_items:
      - demogrp
      - demogrp1
     tags: add_new_group

   - name: Add users
     user:
      name={{ item }}
      state=present
      groups=demogrp
      password="$6$xyz$Jzpc52WWeYmZJxwgLewff/wSUmOTXnY3ITDznE08MSNiy2g/Akl2gHUPL/N2UtpZuJH5LKXF8yFgbP13QYkmY."
      shell=/bin/bash
     with_items:
      - demouser1
      - demouser2
     tags: add_new_user

   - name: Generate ssh key for a user
     user:
      name={{ item }}
      generate_ssh_key=yes
      ssh_key_bits=4096
      ssh_key_file=.ssh/id_rsa
     with_items:
      - demouser1
     become: yes
     tags: generate_ssh_keys
     register: user_new_key

   - name: Update authorized keys for a user
     authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '/home/raja/.ssh/id_rsa.pub') }}"
     with_items:
      - demouser1
     become: yes
     tags: copy_pub_key 

   - name: Delete users
     user:
      name={{ item }}
      state=absent
     with_items:
      - demouser2
     tags: remove_user

   - name: Delete group
     group:
      name={{ item }}
      state=absent
     with_items:
      - demogrp1
     tags: remove_group
